<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HelixToolkit.Wpf" Version="2.27.3" />
    <PackageReference Include="MathNet.Symbolics" Version="0.25.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RD3.Shared\RD3.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="HelixSurfaceView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

</Project>
